ds_source/maestro.py

corrigindo select do status - deixando o nome do cubo como opcional

hotfix inspect status by cubename

---

.gitignore
ds_source/maestro.py
ds_source/soloist.py

Crete new route for restart stucked processes, update number of tasks

route updates

---

bdc_scripts/celery/worker.py
bdc_scripts/radcor/landsat/tasks.py
bdc_scripts/radcor/sentinel/publish.py
bdc_scripts/radcor/sentinel/tasks.py
docker-compose.yml
setup.py

[celery] Fix sentinel publish task

---

bdc_scripts/core/utils.py

fixed generate_cogs to produce valid cogs

---

bdc_scripts/radcor/sentinel/correction.py
bdc_scripts/radcor/sentinel/tasks.py
docker-compose.yml

do not delete files when error occurs & corrected dockerfile atm-correction name

do not delete files when error occurs & corrected dockerfile atm-correction name

---

.gitignore
bdc_scripts/radcor/sentinel/tasks.py

Obtain Sentinel-2 extracted name from zip

---

bdc_scripts/radcor/base_task.py
bdc_scripts/radcor/sentinel/correction.py

Celery rearch recent safe dirs and undo id format

---

bdc_scripts/celery/__init__.py
bdc_scripts/config.py
bdc_scripts/radcor/base_task.py
bdc_scripts/radcor/business.py
bdc_scripts/radcor/landsat/tasks.py
bdc_scripts/radcor/sentinel/download.py
bdc_scripts/radcor/sentinel/tasks.py
setup.py

Close #45 - Task Retry

---

bdc_collection_builder/collections/landsat/publish.py
bdc_collection_builder/collections/sentinel/publish.py
bdc_collection_builder/collections/utils.py

#Close 77 and #Close 108

---

bdc_collection_builder/collections/landsat/publish.py

bugfix publish LC8DN to search tif in any position of matched pattern array

bugfix publish LC8DN match pattern array

---

.gitignore
RUNNING.rst
bdc_collection_builder/cli.py
bdc_collection_builder/config.py
doc/sphinx/index.rst
doc/sphinx/running.rst
docker-compose.yml

Close #76 - Improve documentation workflow

---

bdc_collection_builder/collections/landsat/download.py
bdc_collection_builder/collections/utils.py

Set decompression to None for Landsat products downloaded from AWS 

---

bdc_collection_builder/collections/base_task.py
bdc_collection_builder/collections/controller.py
bdc_collection_builder/collections/landsat/publish.py
bdc_collection_builder/collections/sentinel/correction.py
bdc_collection_builder/collections/sentinel/publish.py
bdc_collection_builder/collections/utils.py
sen2cor/rc_sen2cor.py

Fix sen2cor output directory and minor changes

---

bdc_collection_builder/collections/sentinel/onda.py
bdc_collection_builder/collections/sentinel/tasks.py
secrets.json

Close #146 - Set ONDA as primary external provider

---

bdc_collection_builder/collections/business.py
bdc_collection_builder/collections/controller.py
bdc_collection_builder/collections/landsat/harmonization.py
bdc_collection_builder/collections/landsat/publish.py
bdc_collection_builder/collections/landsat/tasks.py
bdc_collection_builder/collections/nbar.py
bdc_collection_builder/collections/sentinel/correction.py
bdc_collection_builder/collections/sentinel/harmonization.py
bdc_collection_builder/collections/sentinel/publish.py
bdc_collection_builder/collections/sentinel/tasks.py
bdc_collection_builder/collections/sentinel/utils.py
bdc_collection_builder/collections/utils.py
sen2cor/rc_sen2cor.py

New: Sentinel-2 Harmonization
Fix: Landsat-8 Harmonization file names
Fix: Sen2cor output dir

Sentinel-2 Harmonization & fix L8 harm & fix sen2cor output

---

bdc_collection_builder/collections/landsat/tasks.py
bdc_collection_builder/collections/sentinel/tasks.py
bdc_collection_builder/collections/utils.py
bdc_collection_builder/config.py
setup.py

You can enable/disable refresh view using the environment variable ``ENABLE_REFRESH_VIEW``
Close #141

Add option to refresh view on publish

---

bdc_collection_builder/cli.py
bdc_collection_builder/collections/landsat/download.py
bdc_collection_builder/collections/landsat/google.py
bdc_collection_builder/collections/landsat/tasks.py
bdc_collection_builder/collections/landsat/utils.py
bdc_collection_builder/collections/sentinel/utils.py

- Fix minor bug on fmask landsat band - Close #162
- Add NDVI/EVI on load-collections
- #156 - Remove SAFE suffix from collection S2_MSI_L2_SR_LASRC

Minor changes - fix bug google provider and path serialization for Sentinel 2 using LaSRC

---

bdc_collection_builder/collections/landsat/publish.py
bdc_collection_builder/collections/utils.py

Fix minor in raster-convexhull and bug in publish Landsat - BDC-Catalog

---

bdc_collection_builder/collections/utils.py
docker/Dockerfile

fix the code to get the .SAFE folder in the unzip process (correction_lasrc)
- close #184

fix code to get .SAFE folder

---

CHANGES.rst
bdc_collection_builder/celery/publish.py
bdc_collection_builder/celery/tasks.py
bdc_collection_builder/collections/utils.py
bdc_collection_builder/controller.py
bdc_collection_builder/forms.py
bdc_collection_builder/version.py

Minor changes - support trigger by tile and skip item already published

---

bdc_collection_builder/celery/publish.py
bdc_collection_builder/celery/tasks.py
bdc_collection_builder/collections/utils.py
bdc_collection_builder/config.py
bdc_collection_builder/constants.py
bdc_collection_builder/controller.py
bdc_collection_builder/forms.py
bdc_collection_builder/views.py
setup.py

Minor issues for 0.9

---

INSTALL.rst
bdc_collection_builder/celery/__init__.py
bdc_collection_builder/celery/publish.py
docker/Dockerfile
docker/Dockerfile.atm
setup.py

:hammer: Review dependency celery 5+ and setuptools pep517 

---

USING.rst
bdc_collection_builder/celery/publish.py
bdc_collection_builder/celery/tasks.py

- update USING.rst;
- fix publish.py and tasks.py to publish bands and others files from SAFE format file.

feat: publish bands and others files from SAFE format file
